AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  SpringBootApi:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SpringBootApiFunction
      Handler: com.qirised.lambdaexampledemo.StreamLambdaHandler  # 你的 Handler 全限定名
      Runtime: java17
      MemorySize: 1024
      Timeout: 30
      CodeUri: .         # fat-jar 路径
      Events:
        ProxyApi:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
